import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "~/styles/globals.css";
import "~/styles/analog/theme.css";
import "reshaped/themes/reshaped/theme.css";
import { ThemeProvider } from "next-themes";
import { Reshaped } from "reshaped";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-rs-theme="analog" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider defaultTheme="system" attribute="data-rs-color-mode">
          <Reshaped defaultTheme="analog" theme="analog">
            {children}
          </Reshaped>
        </ThemeProvider>
      </body>
    </html>
  );
}
