import type { Metadata } from "next";
import localFont from "next/font/local";
import "~/styles/globals.css";
import { ThemeProvider } from "next-themes";
import { Navbar } from "~/components/navbar";

const hubot = localFont({
  src: "../fonts/Hubot-Sans.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bachitter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${hubot.className}`} suppressHydrationWarning>
      <body className={"antialiased font-body"}>
        <ThemeProvider defaultTheme="system">
          <div className="mx-auto max-w-2xl h-dvh py-4 px-6">
            <div className="mt-20" />
            {children}
            <footer className="fixed max-w-2xl w-full mx-auto bottom-0 bg-gradient-to-t from-background pt-8">
              <Navbar />
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
